language: node_js

group: edge
arch: arm64-graviton2
os: linux
dist: focal
virt: lxd

node_js:
  - 14

install:
  - npm ci
  - cd docs && npm ci && cd ..

script:
  - sed -i 's/^dist\/$//g' .gitignore
  - sed -i 's/^docs\/build\/$//g' .gitignore
  - npm test
  - npm run build
  - cd docs && npx m42kup-builder && cd ..

after_success: npm run coverage

deploy:
  provider: pages
  edge: true
  strategy: git
  cleanup: false
  keep_history: true
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  on:
    branch: master

notifications:
  email:
    recipients:
      - ossia@korea.ac.kr
    on_success: change
    on_failure: always